#!/bin/bash

key_file=$2
code=$(cat $key_file)
code_upper=$(echo $code | tr "a-z" "A-Z")
code_lower=$(echo $code | tr "A-Z" "a-z")
code="$code_upper$code_lower"

function crypt(){
    exit=$(echo "$1" | tr "A-Za-z" "$code")
    echo $exit 
}

function decrypt(){
    exit=$(echo $1 | tr $code "A-Za-z")
    echo $exit
}

a=$(nc $1 5859)
while read line;
do
    line_encrypted=$(crypt "$line")

done
