#!/bin/bash

key_file=$2
code=$(cat $key_file)
code_upper=$(echo $code | tr "a-z" "A-Z")
code_lower=$(echo $code | tr "A-Z" "a-z")
code="$code_upper$code_lower"

function crypt(){
    exit=$(echo "$1" | tr "A-Za-z" "$code")
    echo $exit
}

function decrypt(){
  if [[ "$1" == *"%\$%n"* ]]
  then
    exit=$(echo $1 | rev | cut -f3 -d "%" | rev | tr $code "A-Za-z")
    echo -n "$exit"
  else
    exit=$(echo $1 | tr $code "A-Za-z")
    echo "$exit"
  fi
}

input_fifo=ssn-input-$$
output_fifo=ssn-output-$$

mkfifo "$output_fifo"

mkfifo "$input_fifo"
cat > "$input_fifo" &
echo $! > "$(echo -n $input_fifo)-cat-pid"

tail -f "$input_fifo" | nc "$1" 12345 >> $output_fifo &


while true
do
  if read line < $output_fifo
  then
    line_decrypt=$(decrypt "$line" 2>&1 | tee "/dev/tty")
    if [[ "$line_decrypt" == "Please enter your password: " ]]
    then
      read -s line_in
      crypt $line_in > $input_fifo
    fi

  else
    read line_in
    crypt $line_in > $input_fifo
  fi
done

#while read line < $output_fifo
#do
#  decrypt "$line"
#  read line_in
#  echo "$(crypt "$line_in")" > $input_fifo
#done
